// Official accounts and domains the scam checks protect (scam.js). Offline, no network: shipped with the extension and
// bundled into the worker. Built 2026-09-29 from Fable's smart list and the gold-tick crypto accounts in the capture DB
// (followers are what the DB held that day, in thousands), plus a curated top list of wallets, exchanges and protocols.
// A handle here is always treated as the real account; a lookalike of it is what gets flagged.
//
// ORGS: [handle, display name, followers (k), 'domain ...' (the project's own sites), flags]
//   flags 'w': the brand is also a plain word (Base, Gate, Phantom): a lookalike needs more than the word to count.
export const ORGS = [
  // exchanges
  ['binance', 'Binance', 16154, 'binance.com binance.us binance.info bnbchain.org'],
  ['coinbase', 'Coinbase', 7196, 'coinbase.com cb.com'],
  ['okx', 'OKX', 5603, 'okx.com'],
  ['Bybit_Official', 'Bybit', 4892, 'bybit.com'],
  ['bitget', 'Bitget', 4348, 'bitget.com'],
  ['kucoincom', 'KuCoin', 3517, 'kucoin.com'],
  ['Gate', 'Gate', 2049, 'gate.com gate.io', 'w'],
  ['krakenfx', 'Kraken', 1751, 'kraken.com', 'w'],
  ['MEXC', 'MEXC', 1661, 'mexc.com'],
  ['BingXOfficial', 'BingX', 722, 'bingx.com'],
  ['Gemini', 'Gemini', 631, 'gemini.com', 'w'],
  ['cryptocom', 'Crypto.com', 0, 'crypto.com'],
  ['HTX_Global', 'HTX', 0, 'htx.com'],
  ['Official_Upbit', 'Upbit', 91, 'upbit.com'],
  ['WEEX_Official', 'WEEX', 186, 'weex.com'],
  ['BTCCexchange', 'BTCC', 357, 'btcc.com'],
  ['UpholdInc', 'Uphold', 232, 'uphold.com'],
  ['bitvavocom', 'Bitvavo', 86, 'bitvavo.com'],
  ['_WOO_X', 'WOO X', 255, 'woo.org'],
  ['HyperliquidX', 'Hyperliquid', 428, 'hyperliquid.xyz'],
  ['RobinhoodApp', 'Robinhood', 1387, 'robinhood.com'],
  ['Aster_DEX', 'Aster', 311, 'asterdex.com', 'w'],
  ['Lighter_xyz', 'Lighter', 129, 'lighter.xyz', 'w'],
  ['Backpack', 'Backpack', 325, 'backpack.exchange backpack.app', 'w'],
  ['AxiomExchange', 'Axiom', 114, 'axiom.trade', 'w'],
  ['Polymarket', 'Polymarket', 1990, 'polymarket.com'],
  ['Kalshi', 'Kalshi', 471, 'kalshi.com'],
  ['MetaWin', 'MetaWin', 224, 'metawin.com'],
  // wallets
  ['MetaMask', 'MetaMask', 0, 'metamask.io'],
  ['phantom', 'Phantom', 957, 'phantom.com phantom.app', 'w'],
  ['TrustWallet', 'Trust Wallet', 0, 'trustwallet.com'],
  ['rainbowdotme', 'Rainbow', 0, 'rainbow.me', 'w'],
  ['Ledger', 'Ledger', 676, 'ledger.com', 'w'],
  ['Trezor', 'Trezor', 245, 'trezor.io'],
  ['Rabby_io', 'Rabby Wallet', 156, 'rabby.io'],
  ['zerion', 'Zerion', 321, 'zerion.io'],
  ['exodus_io', 'Exodus', 0, 'exodus.com'],
  ['CoinbaseWallet', 'Coinbase Wallet', 440, 'coinbase.com'],
  ['wallet', 'OKX Wallet', 1862, 'okx.com', 'w'],
  ['BinanceWallet', 'Binance Wallet', 2856, 'binance.com'],
  ['BitgetWallet', 'Bitget Wallet', 0, 'bitget.com web3.bitget.com'],
  ['solflare_wallet', 'Solflare', 0, 'solflare.com'],
  ['SafePal', 'SafePal', 707, 'safepal.com'],
  ['Tangem', 'Tangem', 598, 'tangem.com'],
  ['safe', 'Safe', 132, 'safe.global', 'w'],
  // chains
  ['solana', 'Solana', 4208, 'solana.com'],
  ['ethereum', 'Ethereum', 4546, 'ethereum.org'],
  ['base', 'Base', 1553, 'base.org base.app', 'w'],
  ['BNBCHAIN', 'BNB Chain', 3915, 'bnbchain.org'],
  ['arbitrum', 'Arbitrum', 1150, 'arbitrum.io arbitrum.foundation'],
  ['Optimism', 'Optimism', 727, 'optimism.io'],
  ['0xPolygon', 'Polygon', 2057, 'polygon.technology'],
  ['zksync', 'ZKsync', 1451, 'zksync.io'],
  ['Starknet', 'Starknet', 0, 'starknet.io'],
  ['monad', 'Monad', 1168, 'monad.xyz'],
  ['berachain', 'Berachain', 0, 'berachain.com'],
  ['SuiNetwork', 'Sui', 1092, 'sui.io'],
  ['Aptos', 'Aptos', 0, 'aptosfoundation.org aptoslabs.com'],
  ['ton_blockchain', 'TON', 0, 'ton.org'],
  ['NEARProtocol', 'NEAR Protocol', 1827, 'near.org near.com'],
  ['avax', 'Avalanche', 1103, 'avax.network'],
  ['SeiNetwork', 'Sei', 757, 'sei.io'],
  ['AbstractChain', 'Abstract', 574, 'abs.xyz', 'w'],
  ['Mantle_Official', 'Mantle', 808, 'mantle.xyz', 'w'],
  ['Scroll_ZKP', 'Scroll', 0, 'scroll.io', 'w'],
  ['LineaBuild', 'Linea', 0, 'linea.build'],
  ['Blast_L2', 'Blast', 0, 'blast.io', 'w'],
  ['megaeth', 'MegaETH', 201, 'megaeth.com'],
  ['litecoin', 'Litecoin', 1259, 'litecoin.org litecoin.com'],
  ['MultiversX', 'MultiversX', 973, 'multiversx.com'],
  ['ZetaChain', 'ZetaChain', 988, 'zetachain.com'],
  ['THORChain', 'THORChain', 288, 'thorchain.org'],
  ['Filecoin', 'Filecoin', 649, 'filecoin.io'],
  ['CelestiaOrg', 'Celestia', 0, 'celestia.org'],
  ['XLayerOfficial', 'X Layer', 152, 'okx.com'],
  ['SolanaFndn', 'Solana Foundation', 196, 'solana.org solana.com'],
  ['RobinhoodCrypto', 'Robinhood Crypto', 644, 'robinhood.com'],
  // DeFi, trading and launch apps
  ['Uniswap', 'Uniswap', 1489, 'uniswap.org'],
  ['aave', 'Aave', 702, 'aave.com'],
  ['LidoFinance', 'Lido', 0, 'lido.fi'],
  ['CurveFinance', 'Curve Finance', 381, 'curve.fi curve.finance'],
  ['JupiterExchange', 'Jupiter', 618, 'jup.ag', 'w'],
  ['Raydium', 'Raydium', 464, 'raydium.io'],
  ['Pumpfun', 'Pump.fun', 719, 'pump.fun'],
  ['PancakeSwap', 'PancakeSwap', 2127, 'pancakeswap.finance'],
  ['SushiSwap', 'Sushi', 0, 'sushi.com'],
  ['1inch', '1inch', 0, '1inch.io 1inch.com'],
  ['dYdX', 'dYdX', 0, 'dydx.exchange dydx.trade'],
  ['GMX_IO', 'GMX', 0, 'gmx.io'],
  ['chainlink', 'Chainlink', 1394, 'chain.link'],
  ['LayerZero_Core', 'LayerZero', 714, 'layerzero.network layerzero.foundation'],
  ['wormhole', 'Wormhole', 0, 'wormhole.com'],
  ['jito_sol', 'Jito', 0, 'jito.network'],
  ['ethena', 'Ethena', 247, 'ethena.fi'],
  ['pendle_fi', 'Pendle', 163, 'pendle.finance'],
  ['eigencloud', 'EigenCloud', 306, 'eigencloud.xyz eigenlayer.xyz'],
  ['Ondo', 'Ondo Finance', 384, 'ondo.finance'],
  ['MeteoraAG', 'Meteora', 216, 'meteora.ag'],
  ['orca_so', 'Orca', 192, 'orca.so', 'w'],
  ['sanctumso', 'Sanctum', 80, 'sanctum.so', 'w'],
  ['MarinadeFinance', 'Marinade', 76, 'marinade.finance'],
  ['lifiprotocol', 'LI.FI', 270, 'li.fi jumper.xyz'],
  ['RelayProtocol', 'Relay', 69, 'relay.link', 'w'],
  ['matchaxyz', 'Matcha', 84, 'matcha.xyz', 'w'],
  ['CoWSwap', 'CoW DAO', 68, 'cow.fi'],
  ['PythNetwork', 'Pyth Network', 285, 'pyth.network'],
  ['tether', 'Tether', 569, 'tether.to tether.io'],
  ['circle', 'Circle', 303, 'circle.com', 'w'],
  ['SkyEcosystem', 'Sky', 292, 'sky.money', 'w'],
  ['usualmoney', 'Usual', 108, 'usual.money'],
  ['virtuals_io', 'Virtuals Protocol', 294, 'virtuals.io'],
  ['zora', 'Zora', 273, 'zora.co', 'w'],
  ['opensea', 'OpenSea', 2239, 'opensea.io'],
  ['MagicEden', 'Magic Eden', 0, 'magiceden.io magiceden.us'],
  ['blur_io', 'Blur', 0, 'blur.io', 'w'],
  ['pudgypenguins', 'Pudgy Penguins', 694, 'pudgypenguins.com'],
  ['Azuki', 'Azuki', 428, 'azuki.com'],
  ['DeGodsNFT', 'DeGods', 192, 'degods.com'],
  ['Galxe', 'Galxe', 1510, 'galxe.com'],
  ['gmgnai', 'GMGN', 141, 'gmgn.ai'],
  ['dexscreener', 'DEX Screener', 238, 'dexscreener.com'],
  ['DEXToolsApp', 'DEXTools', 178, 'dextools.io'],
  ['tradewithPhoton', 'Photon', 109, 'photon-sol.tinyastro.io', 'w'],
  ['bananagun', 'Banana Gun', 97, 'bananagun.io'],
  ['ponsdotfamily', 'Pons', 89, 'ponsfamily.com', 'w'],
  ['fomo', 'fomo', 159, 'fomo.family', 'w'],
  ['moonpay', 'MoonPay', 412, 'moonpay.com'],
  ['bonk_inu', 'BONK', 455, 'bonkcoin.com'],
  ['FLOKI', 'FLOKI', 692, 'floki.com'],
  ['ethos_network', 'Ethos', 78, 'ethos.network', 'w'],
  ['KaitoAI', 'Kaito AI', 403, 'kaito.ai'],
  ['arkham', 'Arkham', 1501, 'arkm.com arkhamintelligence.com'],
  ['nansen_ai', 'Nansen', 358, 'nansen.ai'],
  ['coingecko', 'CoinGecko', 2430, 'coingecko.com'],
  ['CoinMarketCap', 'CoinMarketCap', 7115, 'coinmarketcap.com'],
  ['etherscan', 'Etherscan', 161, 'etherscan.io'],
  ['Alchemy', 'Alchemy', 109, 'alchemy.com', 'w'],
  ['Helius', 'Helius', 75, 'helius.dev helius.xyz'],
  ['bubblemaps', 'Bubblemaps', 284, 'bubblemaps.io'],
  ['token2049', 'TOKEN2049', 156, 'token2049.com'],
  // news accounts scammers clone for fake "breaking" airdrops
  ['WatcherGuru', 'Watcher.Guru', 4879, 'watcher.guru'],
  ['CoinDesk', 'CoinDesk', 4073, 'coindesk.com'],
  ['Cointelegraph', 'Cointelegraph', 2936, 'cointelegraph.com'],
  ['BitcoinMagazine', 'Bitcoin Magazine', 4501, 'bitcoinmagazine.com'],
  ['WuBlockchain', 'Wu Blockchain', 558, 'wublock123.com'],
  ['whale_alert', 'Whale Alert', 2852, 'whale-alert.io'],
  ['lookonchain', 'Lookonchain', 712, 'lookonchain.com'],
];

// People scammers clone most: founders, execs, sleuths and the biggest traders. [handle, display name, followers (k)]
export const PEOPLE = [
  ['cz_binance', 'CZ 🔶 BNB', 12942], ['heyibinance', 'Yi He', 638], ['VitalikButerin', 'vitalik.eth', 7946], ['saylor', 'Michael Saylor', 5213],
  ['brian_armstrong', 'Brian Armstrong', 3960], ['justinsuntron', 'H.E. Justin Sun', 4292], ['toly', 'toly', 2734], ['aeyakovenko', 'toly', 2734],
  ['rajgokal', 'raj', 2380], ['haydenzadams', 'Hayden Adams', 2365], ['mert', 'mert', 2335], ['elonmusk', 'Elon Musk', 241714],
  ['StaniKulechov', 'Stani', 305], ['jessepollak', 'jesse.base.eth', 360], ['vladtenev', 'Vlad Tenev', 1077], ['chameleon_jeff', 'jeff.hl', 143],
  ['GracyBitget', 'Gracy Chen', 296], ['star_okx', 'Star Xu', 244], ['paoloardoino', 'Paolo Ardoino', 358], ['jerallaire', 'Jeremy Allaire', 198],
  ['IOHK_Charles', 'Charles Hoskinson', 1060], ['gavofyork', 'Gavin Wood', 443], ['AndreCronjeTech', 'Andre Cronje', 432], ['rleshner', 'Robert Leshner', 2160],
  ['tyler', 'Tyler Winklevoss', 1103], ['cameron', 'Cameron Winklevoss', 758], ['ErikVoorhees', 'Erik Voorhees', 988], ['adam3us', 'Adam Back', 969],
  ['sandeepnailwal', 'Sandeep Nailwal', 348], ['Jihoz_Axie', 'Jihoz', 516], ['LucaNetz', 'Luca Netz', 230], ['a1lon9', 'alon', 419],
  ['NischalShetty', 'Nischal Shetty', 482], ['APompliano', 'Anthony Pompliano', 2417], ['RaoulGMI', 'Raoul Pal', 1500], ['balajis', 'Balaji', 2236],
  ['naval', 'Naval', 4065], ['pmarca', 'Marc Andreessen', 6540], ['cdixon', 'Chris Dixon', 0], ['BillyM2k', 'Shibetoshi Nakamoto', 5015],
  ['zachxbt', 'ZachXBT', 1097], ['samczsun', 'samczsun', 161], ['lookonchain', 'Lookonchain', 712], ['ki_young_ju', 'Ki Young Ju', 434],
  ['blknoiz06', 'Ansem', 1429], ['cobie', 'Cobie', 1242], ['Pentosh1', 'Pentoshi', 948], ['CryptoHayes', 'Arthur Hayes', 814],
  ['MustStopMurad', 'Murad', 727], ['HsakaTrades', 'Hsaka', 599], ['inversebrah', 'smolting', 700], ['frankdegods', 'Frank', 531],
  ['CryptoKaleo', 'K A L E O', 731], ['DonAlt', 'DonAlt', 797], ['CryptoCred', 'Cred', 837], ['TheCryptoDog', 'The Crypto Dog', 848],
  ['CryptoMichNL', 'Michaël van de Poppe', 823], ['elliotrades', 'EllioTrades', 931], ['aantonop', 'Andreas M. Antonopoulos', 784], ['coffeebreak_YT', 'Coffeezilla', 741],
  ['IncomeSharks', 'IncomeSharks', 742], ['trader1sz', 'TraderSZ', 696], ['rektcapital', 'Rekt Capital', 563], ['Trader_XO', 'XO', 551],
  ['AltcoinPsycho', 'AP', 514], ['orangie', 'orangie', 427], ['Rewkang', 'Andrew Kang', 423], ['DaanCrypto', 'Daan Crypto Trades', 415],
  ['notthreadguy', 'threadguy', 411], ['MuroCrypto', 'Muro', 403], ['CryptoNobler', '0xNobler', 386], ['sassal0x', 'sassal.eth', 298],
  ['DefiIgnas', 'Ignas', 164], ['hosseeb', 'Haseeb Qureshi', 0], ['lopp', 'Jameson Lopp', 532], ['scottmelker', 'The Wolf Of All Streets', 1086],
  ['WazzCrypto', 'Wazz', 61], ['benjamincowen', 'Benjamin Cowen', 1266], ['PeterSchiff', 'Peter Schiff', 1753], ['woonomic', 'Willy Woo', 0],
  ['cryptorover', 'Crypto Rover', 1616], ['AshCrypto', 'Ash Crypto', 2163], ['NoLimitGains', 'NoLimit', 1512],
];

// Real secondary accounts of the brands above (support desks, regional and product accounts): never lookalikes.
export const OFFICIAL_ALTS = ['CoinbaseSupport', 'CoinbaseDev', 'CoinbaseAssets', 'coinbasepro', 'BinanceHelpDesk', 'BinanceUS', 'binancezh', 'BinanceAcademy',
  'BinanceResearch', 'binance_es', 'Binance_Africa', 'MetaMaskSupport', 'MetaMaskDev', 'PhantomSupport', 'krakensupport', 'krakenpro', 'LedgerSupport',
  'Ledger_Support', 'TrezorSupport', 'OKXHelpDesk', 'okxweb3', 'Bybit_Help', 'BybitHelp', 'KuCoinSupport', 'Uniswap_Labs', 'UniswapFND', 'arbitrum_dao',
  'SolanaFndn', 'solana_devs', 'solanamobile', 'solanagaming', 'SolanaEvents', 'jup_mobile', 'PumpfunEco', 'PolymarketMoney', 'PolymarketSport',
  'OpenSeaSupport', 'MagicEden_Help', 'RobinhoodCrypto', 'krakenfx', 'buildonbase', 'BaseAppSupport', 'baseapp', 'TrustWalletApp', 'Trust_Wallet',
  'BitgetWalletApp', 'bitgetglobal', 'sanctumapp', 'MEXC_Official', 'gate_io', 'Gate_io', 'HyperliquidLabs', 'LidoSupport', 'aaveaave', 'AaveAave'];

// Official tokens of legit launchpads and protocols, vouched for by hand (owner rule, 2026-10-02: "Pons is a legitimate
// launchpad, and $PONS is its token. It must NEVER be flagged as high risk / scam / shill"). Matched by exact contract
// address only: a copy with the same ticker on another contract is judged on its own evidence. No automated token rule
// (scam-KOL mentions, promotion rings, co-posting waves, scanner flags) turns these red or amber; what Fable read about
// them stays visible as neutral facts. Sources for Pons: overhaul/registry-infra/PONS.md (ponsfamily.com, the official
// GitHub README, DefiLlama).
// [chain, address, symbol, what it is, 'official handles']
export const OFFICIAL_TOKENS = [
  ['robinhood', '0x39dbed3a2bd333467115de45665cc57f813c4571', 'PONS', 'Pons, the Robinhood Chain launchpad', 'ponsdotfamily MEADgod'],
];

// Tickers of established coins (CoinGecko top 100 and blue-chip protocols, overhaul/registry-major established.json,
// 2026-09-28), plus the official tokens above. A "$ZEC" in a post with no contract means Zcash: scam-KOL mentions of the
// ticker are about the posters, never a flag on the coin. Tickers that are also plain words or shared by many memecoins
// (M, U, W, RAIN, PUMP, BABY, CLOUD, STABLE ...) are left out on purpose.
export const PROTECTED_TICKERS = ['BTC', 'ETH', 'USDT', 'BNB', 'XRP', 'USDC', 'SOL', 'TRX', 'ZEC', 'HYPE', 'DOGE', 'LINK', 'XMR', 'ADA', 'LEO', 'XLM',
  'NEAR', 'BCH', 'UNI', 'LTC', 'SUI', 'USDE', 'AVAX', 'DAI', 'HBAR', 'QNT', 'TAO', 'SHIB', 'CRO', 'XAUT', 'ONDO', 'ENA', 'PYUSD', 'OKB', 'AAVE', 'MNT',
  'DOT', 'WLD', 'ASTER', 'MORPHO', 'WLFI', 'PAXG', 'PEPE', 'ICP', 'ARB', 'ETC', 'BGB', 'KAS', 'POL', 'JUP', 'ALGO', 'RENDER', 'CAKE', 'ATOM', 'FIL',
  'NEXO', 'DASH', 'AERO', 'VET', 'INJ', 'APT', 'XDC', 'PYTH', 'PENGU', 'ZRO', 'RAY', 'CRV', 'PENDLE', 'LDO', 'JTO', 'EIGEN', 'COMP', 'TON', 'WBTC',
  'WETH', 'STETH', ...OFFICIAL_TOKENS.map((x) => x[2])];
